---
log_filepath:
  description: Path to the file, relative to working directory, where the log will be stored
  value: ./cert_processing_log.txt
smallest_certificate_id_to_connect:
  description:
    During validation we don't connect certificates with number lower than
    _this_ to connections
  value: 40
year_difference_between_validations:
  description:
    During validation we don't connect certificates with validation dates
    difference higher than _this_
  value: 7
use_text_with_newlines_during_parsing:
  description: During keyword search, search in text with newlines
  value: true
n_threads:
  description: How many threads to use for parallel computations
  value: 8
cpe_matching_threshold:
  description: Level of required string similarity between CPE and certificate name on CC CPE matching, 0-100. Lower values yield more false negatives, higher values more false positives
  value: 90
cpe_n_max_matches:
  description: Maximum number of candidate CPE items that may be related to given certificate, >0
  value: 100
cc_latest_snapshot:
  description: Url from where to fetch the latest snapshot of fully processed CC dataset
  value: https://seccerts.org/cc/dataset.json
cc_maintenances_latest_snapshot:
  description: Url from where to fetch the latest snapshot of CC maintenance updates
  value: https://seccerts.org/cc/maintenance_updates.json
ignore_first_page:
  description: During keyword search, first page usually contains addresses - ignore it.
  value: true
cert_threshold:
  description: Used with --higher-precision-results. Determines the amount of mismatched algorithms to be considered faulty.
  value: 5
fips_latest_snapshot:
  description: Url for the latest snapshot of FIPS dataset
  value: https://seccerts.org/fips/dataset.json
minimal_token_length:
  description: Minimal length of a string that will be considered as a token during keyword extraction in CVE matching
  value: 3
enable_progress_bars:
  description: Whether to enable pretty-printed progress bars while processing.
  value: true
